"""0001

Revision ID: d7a0bda00f21
Revises: 
Create Date: 2025-05-02 01:47:40.874982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a0bda00f21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('operations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('enterprises',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('estate', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['estate'], ['estates.address'], ),
    sa.ForeignKeyConstraint(['operation'], ['operations.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprises')
    op.drop_table('operations')
    op.drop_table('estates')
    # ### end Alembic commands ###
